_BASE_: "../base/Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "PNASemanticSegmentor"
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    RETURN_INPUT: True
  SEM_SEG_HEAD:
    NAME: "PNASemSegHead" 
    COARSE_SEM_SEG_HEAD_NAME: "SemSegFPNHead" 
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 19
    LOSS_TYPE: "hard_pixel_mining" 
  PNA_HEAD:
    NUM_CLASSES: 19
    IN_FEATURES: ["res2", "res3", "res4", "res5"] 
    COMMON_STRIDE: 4
    WINDOW_SIZE: [9, 9, 9, 9]
    EMBED_DIMS: [96, 192, 384, 768]
    LOSS_TYPE: "hard_pixel_mining" 
    LOSS_WEIGHT: 0.1
  RESNETS:
    DEPTH: 101
    NORM: "SyncBN"
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128 
    STRIDE_IN_1X1: false
  
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MAX_ITER: 90000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.01
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
  
TEST:
  EVAL_PERIOD: 9000
 
DATALOADER:
  NUM_WORKERS: 10