_BASE_: "../base/Base-Semantic-FPN.yaml"
MODEL: 
  WEIGHTS: "detectron2://DeepLab/R-52.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375] 
  RESNETS:
    DEPTH: 50 
 
  SEM_SEG_HEAD:
    NUM_CLASSES: 7  
    LOSS_TYPE: "hard_pixel_mining"
    
  PNA_HEAD:
    NUM_CLASSES: 7  
    WINDOW_SIZE: [7, 7, 7, 7]
    LOSS_TYPE: "hard_pixel_mining"

DATASETS:
  TRAIN: ("deep_globe_train",)
  TEST: ("deep_globe_val",)
  
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (508, 508)
    SINGLE_CATEGORY_MAX_AREA: 0.75 
  COLOR_AUG_SSD: True
  FORMAT: "RGB"
  
SOLVER:      
  IMS_PER_BATCH: 16
  MAX_ITER: 4000 
  CHECKPOINT_PERIOD: 4000

TEST:
    EVAL_PERIOD: 400