_BASE_: "../base/Base-Semantic-FPN.yaml"
MODEL: 
  SEM_SEG_HEAD: 
    NUM_CLASSES: 19
    LOSS_TYPE: "hard_pixel_mining" 
  PNA_HEAD: 
    IN_FEATURES: ["res2", "res3", "res4", "res5"] 
    COMMON_STRIDE: 4
    EMBED_DIMS: [96, 192, 384, 768]
    WINDOW_SIZE: [7, 7, 7, 7]
    NUM_CLASSES: 19
    LOSS_TYPE: cross_entropy
    
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
SOLVER:  
  MAX_ITER: 90000 

INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 0.75
  COLOR_AUG_SSD: True
  FORMAT: RGB
TEST:
    EVAL_PERIOD: 9000